In [2]:
import pandas as pd
from numpy.random import randn
from numpy.random import seed
from scipy.stats import pearsonr
from scipy import stats

pd.set_option("display.max_rows", 101)
pd.set_option("display.max_columns", 101)

In [3]:
df = pd.read_csv('/Users/markdetiberiis/Desktop/Citibike_data/df_ready_for_eda.csv')

In [4]:
df.drop(['Unnamed: 0'], axis = 1, inplace = True)

In [5]:
# Modfying zipcode to the correct format
df.citi_zipcode = df.citi_zipcode.astype(str)
df.citi_zipcode = df.citi_zipcode.apply(lambda x: x[0:5])
df.citi_zipcode = df.citi_zipcode.apply(lambda x: x.strip('.'))
df.citi_zipcode = df.citi_zipcode.apply(lambda x: '0'+ x if x.startswith('7') else x)

In [6]:
df = df[~df.citi_zipcode.str.startswith("1")]

In [7]:
df.corr(method = 'spearman')

,station_id,tripduration,citi_station_lat,citi_station_lon,PRCP,TAVG,dist_mta,train_lat,train_lon,landmark_lat,landmark_lon,dist_landmark,Median,Mean,Pop,rider,weekend
station_id,1.000000,-0.001022,-0.069350,0.063087,-0.000319,-0.006115,0.084944,-0.039128,0.039128,0.004313,0.184240,0.031159,0.172600,0.184620,-0.182295,NaN,0.005980
tripduration,-0.001022,1.000000,-0.051492,-0.035804,-0.034959,0.243041,0.155115,0.144851,-0.144851,-0.002889,0.062169,0.071931,-0.035434,-0.022222,0.025245,NaN,0.199986
citi_station_lat,-0.069350,-0.051492,1.000000,-0.214528,0.015684,-0.035584,-0.423981,0.223151,-0.223151,0.005028,0.022214,-0.808938,-0.210973,-0.253115,0.256482,NaN,-0.043294
citi_station_lon,0.063087,-0.035804,-0.214528,1.000000,-0.011488,0.025075,-0.439234,-0.744186,0.744186,-0.003208,0.722007,-0.208777,0.799158,0.793604,-0.788844,NaN,0.022088
PRCP,-0.000319,-0.034959,0.015684,-0.011488,1.000000,0.023123,-0.011089,0.009896,-0.009896,0.001166,-0.006848,-0.002881,-0.016862,-0.017994,0.017773,NaN,-0.134311
TAVG,-0.006115,0.243041,-0.035584,0.025075,0.023123,1.000000,0.037682,-0.001357,0.001357,-0.001551,0.039075,0.024990,0.020624,0.026963,-0.026793,NaN,0.072703
dist_mta,0.084944,0.155115,-0.423981,-0.439234,-0.011089,0.037682,1.000000,0.204411,-0.204411,NaN,-0.431097,0.495244,-0.272727,-0.218879,0.224746,NaN,0.040190
train_lat,-0.039128,0.144851,0.223151,-0.744186,0.009896,-0.001357,0.204411,1.000000,-1.000000,NaN,-0.302319,0.227520,-0.694061,-0.694061,0.689887,NaN,-0.012266
train_lon,0.039128,-0.144851,-0.223151,0.744186,-0.009896,0.001357,-0.204411,-1.000000,1.000000,NaN,0.302319,-0.227520,0.694061,0.694061,-0.689887,NaN,0.012266
landmark_lat,0.004313,-0.002889,0.005028,-0.003208,0.001166,-0.001551,NaN,NaN,NaN,1.000000,-0.004443,0.000668,NaN,NaN,NaN,NaN,-0.000229
landmark_lon,0.184240,0.062169,0.022214,0.722007,-0.006848,0.039075,-0.431097,-0.302319,0.302319,-0.004443,1.000000,-0.219070,0.689739,0.689739,-0.689739,NaN,0.022433
dist_landmark,0.031159,0.071931,-0.808938,-0.208777,-0.002881,0.024990,0.495244,0.227520,-0.227520,0.000668,-0.219070,1.000000,-0.232799,-0.186961,0.173979,NaN,0.022256
Median,0.172600,-0.035434,-0.210973,0.799158,-0.016862,0.020624,-0.272727,-0.694061,0.694061,NaN,0.689739,-0.232799,1.000000,0.990488,-0.986054,NaN,0.031511
Mean,0.184620,-0.022222,-0.253115,0.793604,-0.017994,0.026963,-0.218879,-0.694061,0.694061,NaN,0.689739,-0.186961,0.990488,1.000000,-0.997975,NaN,0.035414
Pop,-0.182295,0.025245,0.256482,-0.788844,0.017773,-0.026793,0.224746,0.689887,-0.689887,NaN,-0.689739,0.173979,-0.986054,-0.997975,1.000000,NaN,-0.035129
rider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weekend,0.005980,0.199986,-0.043294,0.022088,-0.134311,0.072703,0.040190,-0.012266,0.012266,-0.000229,0.022433,0.022256,0.031511,0.035414,-0.035129,NaN,1.000000

In [8]:
df_temp = df[['TAVG', 'rider']].copy()

In [9]:
corr_temp = df.groupby(['TAVG']).corr(method = 'spearman', min_periods = 1)
corr_temp

                       station_id  tripduration  citi_station_lat  \
TAVG
22.0 station_id          1.000000      0.078959         -0.173380
     tripduration        0.078959      1.000000         -0.035001
     citi_station_lat   -0.173380     -0.035001          1.000000
     citi_station_lon    0.054547     -0.055422         -0.339248
     PRCP                     NaN           NaN               NaN
...                           ...           ...               ...
90.0 Median              0.091745     -0.012566         -0.048961
     Mean                0.097497      0.013161         -0.103549
     Pop                -0.093341     -0.006058          0.108069
     rider                    NaN           NaN               NaN
     weekend                  NaN           NaN               NaN

                       citi_station_lon  PRCP  dist_mta  train_lat  train_lon  \
TAVG
22.0 station_id                0.054547   NaN  0.204517  -0.009413   0.009413
     tripduration             -0.055422   NaN  0.097774   0.163511  -0.163511
     citi_station_lat         -0.339248   NaN -0.341979   0.422357  -0.422357
     citi_station_lon          1.000000   NaN -0.436729  -0.729300   0.729300
     PRCP                           NaN   NaN       NaN        NaN        NaN
...                                 ...   ...       ...        ...        ...
90.0 Median                    0.808254   NaN -0.388638  -0.710943   0.710943
     Mean                      0.799332   NaN -0.315586  -0.710943   0.710943
     Pop                      -0.790090   NaN  0.324734   0.701487  -0.701487
     rider                          NaN   NaN       NaN        NaN        NaN
     weekend                        NaN   NaN       NaN        NaN        NaN

                       landmark_lat  landmark_lon  dist_landmark    Median  \
TAVG
22.0 station_id                 NaN      0.196714       0.158983  0.113207
     tripduration               NaN      0.046115       0.103017 -0.106832
     citi_station_lat           NaN      0.049390      -0.753088 -0.284376
     citi_station_lon           NaN      0.671722      -0.173377  0.819032
     PRCP                       NaN           NaN            NaN       NaN
...                             ...           ...            ...       ...
90.0 Median                     NaN      0.674055      -0.445824  1.000000
     Mean                       NaN      0.674055      -0.389299  0.984901
     Pop                        NaN     -0.674055       0.368721 -0.977589
     rider                      NaN           NaN            NaN       NaN
     weekend                    NaN           NaN            NaN       NaN

                           Mean       Pop  rider  weekend
TAVG
22.0 station_id        0.136599 -0.139076    NaN      NaN
     tripduration     -0.091823  0.092850    NaN      NaN
     citi_station_lat -0.330331  0.338398    NaN      NaN
     citi_station_lon  0.812817 -0.809822    NaN      NaN
     PRCP                   NaN       NaN    NaN      NaN
...                         ...       ...    ...      ...
90.0 Median            0.984901 -0.977589    NaN      NaN
     Mean              1.000000 -0.995701    NaN      NaN
     Pop              -0.995701  1.000000    NaN      NaN
     rider                  NaN       NaN    NaN      NaN
     weekend                NaN       NaN    NaN      NaN

[1040 rows x 16 columns]

AVG Daily Riders & Precipitation

In [11]:
#avg daily riders by PRCP

df_rain = pd.DataFrame(df.groupby(['PRCP', 'date'])['rider'].sum().median(level='PRCP'))

In [12]:
df_rain['prcp'] = df_rain.index

In [13]:
#Pearson correlation prcp v avg daily riders

corr_prcp = df_rain.corr(method = 'pearson', min_periods = 1)
corr_prcp

          rider      prcp
rider  1.000000 -0.286872
prcp  -0.286872  1.000000

In [15]:
#p
R, p = stats.pearsonr(df_rain['rider'],df_rain['prcp'])

print("R: %f    p_value: %f"%(R,p))

R: -0.286872    p_value: 0.021546

AVG Daily Riders & TAVG

In [17]:
#avg daily riders by TAVG

df_TAVG = pd.DataFrame(df.groupby(['TAVG', 'date'])['rider'].sum().median(level='TAVG'))

In [18]:
df_TAVG['tavg'] = df_TAVG.index

In [88]:
#Pearson correlation TAVG v avg daily riders

corr_TAVG = df_TAVG.corr(method = 'pearson', min_periods = 1)
corr_TAVG

          rider      tavg
rider  1.000000  0.745778
tavg   0.745778  1.000000

In [20]:
#p 

R, p = stats.pearsonr(df_TAVG['rider'],df_TAVG['tavg'])

print("R: %f    p_value: %f"%(R,p))

R: 0.745778    p_value: 0.000000

Riders & Income

In [21]:
df_income = pd.DataFrame(df.groupby(['Median', 'date'])['rider'].sum().median(level='Median'))

In [22]:
df_income['Median'] = df_income.index

In [23]:
corr_income = df_income.corr(method = 'pearson', min_periods = 1)
corr_income

           rider    Median
rider   1.000000  0.152867
Median  0.152867  1.000000

In [25]:
#p 

R, p = stats.pearsonr(df_income['rider'],df_income['Median'])

print("R: %f    p_value: %f"%(R,p))

R: 0.152867    p_value: 0.717809